type
  Python2NimError* = object of Exception
